---
title: "1monthmalenpc"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
suppressMessages(library(Seurat))
suppressMessages(library(dplyr))
suppressMessages(library(org.Mm.eg.db))
suppressMessages(library(biomaRt))
suppressMessages(library(clusterProfiler))
suppressMessages(library(SingleR))
```

```{r pressure, echo=FALSE}
object1.data <- Read10X(data.dir = "/Users/brucewanglab/Documents/scRNAseq_data/Maca_filtered/10X_P5_7_filtered")
Pliver <- CreateSeuratObject(counts = object1.data, min.cells = 3, min.features = 0, project = "mouse1")
```

```{r}
Pliver
print(paste("Avg nGene:", mean(Pliver$nFeature_RNA), sep = " "))
print(paste("Avg nUMI:", mean(Pliver$nCount_RNA), sep = " "))
```

```{r}
Pliver[["percent.mt"]] <- PercentageFeatureSet(object = Pliver, pattern = "^mt-")
plot1 <- FeatureScatter(object = Pliver, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(object = Pliver, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
CombinePlots(plots = list(plot1, plot2))
```

```{r}
VlnPlot(object = Pliver, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
Pliver <- subset(x = Pliver, subset = nFeature_RNA > 500 & nFeature_RNA < 4000 & nCount_RNA > 200 & nCount_RNA < 20000)
```

```{r}
Pliver
print(paste("Avg nGene:", mean(Pliver$nFeature_RNA), sep = " "))
print(paste("Avg nUMI:", mean(Pliver$nCount_RNA), sep = " "))
```

```{r}
Pliver <- NormalizeData(object = Pliver, normalization.method = "LogNormalize", scale.factor = 10000)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}

Pliver <- FindVariableFeatures(object = Pliver, selection.method = "vst", nfeatures = 2000)


top10 <- head(x = VariableFeatures(object = Pliver), 10)


plot1 <- VariableFeaturePlot(object = Pliver)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1, plot2))
```

```{r}
all.genes <- rownames(x = Pliver)
Pliver <- ScaleData(object = Pliver, features = all.genes) #vars.to.regress = "orig.ident")
```

```{r}
Pliver <- RunPCA(Pliver, features = VariableFeatures(object = Pliver))
```

```{r}
VizDimLoadings(Pliver, dims = 1:2, reduction = "pca")
```

```{r}
DimPlot(Pliver, reduction = "pca")
```

```{r, echo=FALSE, fig.height=10, fig.width=8}
DimHeatmap(Pliver, dims = 1:10, cells = 500, balanced = TRUE)
```

```{r}
ElbowPlot(Pliver)
```

```{r}
n_pcs <- 10


res <- 0.3

Pliver <- FindNeighbors(Pliver, dims = 1:n_pcs)
Pliver <- FindClusters(Pliver, resolution = res)
```

```{r}
Pliver <- RunUMAP(Pliver, dims = 1:n_pcs)
DimPlot(Pliver, reduction = "umap")
```

```{r}
genes_hep = c('Alb', 'Ttr', 'Apoa1', 'Serpina1c', 
                   'Cyp2e1', 'Glul', 'Slc1a2', 'Oat', 'Gulo',
                   'Ass1', 'Hamp', 'Gstp1', 'Ubb',
                   'Cyp2f2', 'Pck1', 'Hal', 'Cdh1', 'Cps1')
genes_endo = c('Pecam1', 'Nrp1', 'Kdr','Oit3', 'Flt4')
genes_stellate = c('Dcn','Col1a2', 'Bgn')
genes_kuppfer = c('Clec4f', 'Cd68', 'Irf7')
genes_nk = c('Zap70', 'Il2rb', 'Nkg7','Cxcr6', 'Gzma', 'Klrb1c')
genes_b = c('Cd79a','Cd79b', 'Cd74')
genes_bec = c('Epcam', 'Krt19', 'Krt7', 'Spp1', 'Sox9')
genes_immune = 'Ptprc'
genes_neutrophil = c('Csf3r','Csf3r', 'Cxcr2')
genes_pDC = c('Siglech', 'Bst2', 'Ly6c2', 'Tlr7', 'Itgax', 'Irf8')
genes_monocyte = c("Itgam", "Csf1r", "Ly6c2","Cx3cr1", "Ccr2", "Cd14")

all_genes = c(genes_endo, genes_kuppfer, genes_nk, genes_b, genes_bec, genes_immune, genes_stellate)
```

```{r, fig.height=12, fig.width=15}
FeaturePlot(object = Pliver, features = genes_hep, cols = c("grey", "blue"), reduction = "umap")
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(Pliver, features = genes_hep)
```

```{r}
nonhep <- SubsetData(object = Pliver, ident.remove = c(2))
```

```{r}
nonhep
print(paste("Avg nGene:", mean(nonhep$nFeature_RNA), sep = " "))
print(paste("Avg nUMI:", mean(nonhep$nCount_RNA), sep = " "))
```

```{r}
VlnPlot(object = nonhep, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
nonhep <- FindVariableFeatures(object = nonhep, selection.method = "vst", nfeatures = 2000)
```

```{r}
all.genes <- rownames(x = nonhep)
nonhep <- ScaleData(object = nonhep, features = all.genes)#, vars.to.regress = "orig.ident")
```

```{r}
nonhep <- RunPCA(nonhep, features = VariableFeatures(object = nonhep))
```

```{r}
DimPlot(nonhep, reduction = "pca")
```

```{r}
ElbowPlot(nonhep)
```

```{r}
#TODO: Set sub.n.pcs to number of PCs you wish to use.
sub_n_pcs = 10

#TODO: Set resolution 
sub_res <- 0.3

nonhep <- FindNeighbors(nonhep, dims = 1:sub_n_pcs)
nonhep <- FindClusters(nonhep, resolution = sub_res)
```

```{r}
nonhep <- RunUMAP(nonhep, dims = 1:sub_n_pcs)
DimPlot(nonhep, reduction = "umap")
```

```{r}
nonhep <- RunTSNE(object = nonhep, dims.use = 1:sub_n_pcs, seed.use = 10)
```

```{r}
TSNEPlot(object = nonhep, do.label = TRUE)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = nonhep, features = genes_endo)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = nonhep, features = genes_stellate)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = nonhep, features = genes_kuppfer)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = nonhep, features = genes_nk)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = nonhep, features = genes_b)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = nonhep, features = genes_bec)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = nonhep, features = c("Bpgm", "Gypa"))
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = nonhep, features = genes_pDC)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = nonhep, features = genes_monocyte)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = nonhep, features = genes_neutrophil)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = nonhep, features = genes_immune)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
FeaturePlot(object = nonhep, features = c("nFeature_RNA", "nCount_RNA"))
```

```{r}
nonhep <- RenameIdents(object = nonhep, "0" = "kuppfer cells")
nonhep <- RenameIdents(object = nonhep, "1" = "endothelial cells")
nonhep <- RenameIdents(object = nonhep, "2" = "kuppfer cells")
nonhep <- RenameIdents(object = nonhep, "3" = "kuppfer cells")
nonhep <- RenameIdents(object = nonhep, "4" = "nk cells")
nonhep <- RenameIdents(object = nonhep, "5" = "nk cell")
nonhep <- RenameIdents(object = nonhep, "6" = "b cells")
nonhep <- RenameIdents(object = nonhep, "7" = "endothelial cells")
nonhep <- RenameIdents(object = nonhep, "8" = "stellate cells")
nonhep <- RenameIdents(object = nonhep, "9" = "unknown")
nonhep <- RenameIdents(object = nonhep, "10" = "pDC")
nonhep <- RenameIdents(object = nonhep, "11" = "bec")
```

```{r}
nonhep <- RenameIdents(object = nonhep, "nk cell" = "nk cells")
```

```{r}
nonhep <- RenameIdents(object = nonhep, "unknown" = "monocytes")
```

```{r}
DimPlot(nonhep, reduction = "umap")
```

```{r}
save(nonhep, file = "/Users/brucewanglab/Documents/Jaiveer/1\ month\1monthmalenpc.Robj")
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

