---
title: "21monthfemalenpc"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
suppressMessages(library(Seurat))
suppressMessages(library(dplyr))
suppressMessages(library(org.Mm.eg.db))
suppressMessages(library(biomaRt))
suppressMessages(library(clusterProfiler))
suppressMessages(library(SingleR))
```

```{r pressure, echo=FALSE}
fmouse1.data <- Read10X(data.dir = "/Users/brucewanglab/Documents/scRNAseq_data/Maca_filtered/MACA_21m_F_NPC_54_filtered")
fmouse1 <- CreateSeuratObject(counts = fmouse1.data, min.cells = 3, min.features = 0, project = "mouse1")
```

```{r}
fmouse1
print(paste("Avg nGene:", mean(fmouse1$nFeature_RNA), sep = " "))
print(paste("Avg nUMI:", mean(fmouse1$nCount_RNA), sep = " "))
```

```{r}
fmouse1[["percent.mt"]] <- PercentageFeatureSet(object = fmouse1, pattern = "^mt-")
plot1 <- FeatureScatter(object = fmouse1, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(object = fmouse1, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
CombinePlots(plots = list(plot1, plot2))
```

```{r}
VlnPlot(object = fmouse1, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
fmouse1 <- subset(x = fmouse1, subset = nFeature_RNA > 100 & nFeature_RNA < 3000 & nCount_RNA > 200 & nCount_RNA < 15000)
```

```{r}
fmouse1
print(paste("Avg nGene:", mean(fmouse1$nFeature_RNA), sep = " "))
print(paste("Avg nUMI:", mean(fmouse1$nCount_RNA), sep = " "))
```

```{r}
fmouse1<- NormalizeData(object = fmouse1, normalization.method = "LogNormalize", scale.factor = 10000)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}

fmouse1 <- FindVariableFeatures(object = fmouse1, selection.method = "vst", nfeatures = 2000)


top10 <- head(x = VariableFeatures(object = fmouse1), 10)


plot1 <- VariableFeaturePlot(object = fmouse1)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1, plot2))
```

```{r}
all.genes <- rownames(x = fmouse1)
fmouse1 <- ScaleData(object = fmouse1, features = all.genes) #vars.to.regress = "orig.ident")
```

```{r}
fmouse1 <- RunPCA(fmouse1, features = VariableFeatures(object = fmouse1))
```

```{r}
DimPlot(fmouse1, reduction = "pca")
```

```{r}
ElbowPlot(fmouse1)
```

```{r}
n_pcs <- 10


res <- 0.5

fmouse1 <- FindNeighbors(fmouse1, dims = 1:n_pcs)
fmouse1 <- FindClusters(fmouse1, resolution = res)
```

```{r}
fmouse1 <- RunUMAP(fmouse1, dims = 1:n_pcs)
DimPlot(fmouse1, reduction = "umap")
```

```{r}
genes_hep = c('Alb', 'Ttr', 'Apoa1', 'Serpina1c', 
                   'Cyp2e1', 'Glul', 'Slc1a2', 'Oat', 'Gulo',
                   'Ass1', 'Hamp', 'Gstp1', 'Ubb',
                   'Cyp2f2', 'Pck1', 'Hal', 'Cdh1', 'Cps1')
genes_endo = c('Pecam1', 'Nrp1', 'Kdr','Oit3', 'Flt4')
genes_stellate = c('Dcn','Col1a2', 'Bgn')
genes_kuppfer = c('Clec4f', 'Cd68', 'Irf7')
genes_nk = c('Zap70', 'Il2rb', 'Nkg7','Cxcr6', 'Gzma', 'Klrb1c')
genes_b = c('Cd79a','Cd79b', 'Cd74')
genes_bec = c('Epcam', 'Krt19', 'Krt7', 'Spp1', 'Sox9')
genes_immune = 'Ptprc'
genes_neutrophil = c('Csf3r','Csf3r', 'Cxcr2')
genes_pDC = c('Siglech', 'Bst2', 'Ly6c2', 'Tlr7', 'Itgax', 'Irf8')
genes_monocyte = c("Itgam", "Csf1r", "Ly6c2","Cx3cr1", "Ccr2", "Cd14")

all_genes = c(genes_endo, genes_kuppfer, genes_nk, genes_b, genes_bec, genes_immune, genes_stellate)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(fmouse1, features = genes_hep)
```

```{r}
npc <- SubsetData(object = fmouse1, ident.remove = c(1,5,6))
```

```{r}
npc
print(paste("Avg nGene:", mean(npc$nFeature_RNA), sep = " "))
print(paste("Avg nUMI:", mean(npc$nCount_RNA), sep = " "))
```

```{r}
VlnPlot(object = npc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
npc <- FindVariableFeatures(object = npc, selection.method = "vst", nfeatures = 2000)
```

```{r}
all.genes <- rownames(x = npc)
npc <- ScaleData(object = npc, features = all.genes)#, vars.to.regress = "orig.ident")
```

```{r}
npc <- RunPCA(npc, features = VariableFeatures(object = npc))
```

```{r}
DimPlot(npc, reduction = "pca")
```


```{r}
ElbowPlot(npc)
```

```{r}
#TODO: Set sub.n.pcs to number of PCs you wish to use.
sub_n_pcs = 10

#TODO: Set resolution 
sub_res <- 0.4

npc <- FindNeighbors(npc, dims = 1:sub_n_pcs)
npc <- FindClusters(npc, resolution = sub_res)
```

```{r}
npc <- RunUMAP(npc, dims = 1:sub_n_pcs)
DimPlot(npc, reduction = "umap")
```

```{r}
npc <- RunTSNE(object = npc, dims.use = 1:sub_n_pcs, seed.use = 10)
```

```{r}
TSNEPlot(object = npc, do.label = TRUE)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = npc, features = genes_endo)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = npc, features = genes_stellate)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = npc, features = genes_kuppfer)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = npc, features = genes_nk)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = npc, features = genes_b)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = npc, features = genes_bec)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = npc, features = c("Bpgm", "Gypa"))
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
VlnPlot(object = npc, features = genes_pDC)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
FeaturePlot(object = npc, features = c("nFeature_RNA", "nCount_RNA"))
```

```{r}
npc <- RenameIdents(object = npc, "0" = "stellate cells")
npc <- RenameIdents(object = npc, "1" = "b cells")
npc <- RenameIdents(object = npc, "2"= "endothelial cells")
npc <- RenameIdents(object = npc, "3" = "bec")
npc <- RenameIdents(object = npc, "4" = "stellate cells")
npc <- RenameIdents(object = npc, "5" = "nk cells")
npc <- RenameIdents(object = npc, "6" = "endothelial cells")
```

```{r}
DimPlot(npc, reduction = "umap")
```

```{r}
stellate <- SubsetData(object = npc, ident.use = c("stellate cells"))
```

```{r}
stellate
print(paste("Avg nGene:", mean(stellate$nFeature_RNA), sep = " "))
print(paste("Avg nUMI:", mean(stellate$nCount_RNA), sep = " "))
```

```{r}
VlnPlot(object = stellate, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
stellate <- FindVariableFeatures(object = stellate, selection.method = "vst", nfeatures = 2000)
```

```{r}
all.genes <- rownames(x = stellate)
stellate <- ScaleData(object = stellate, features = all.genes)#, vars.to.regress = "orig.ident")
```

```{r}
stellate <- RunPCA(stellate, features = VariableFeatures(object = stellate))
```

```{r}
DimPlot(stellate, reduction = "pca")
```

```{r}
ElbowPlot(stellate)
```

```{r}
#TODO: Set sub.n.pcs to number of PCs you wish to use.
sub_n_pcs = 10

#TODO: Set resolution 
sub_res <- 0.3

stellate <- FindNeighbors(stellate, dims = 1:sub_n_pcs)
stellate <- FindClusters(stellate, resolution = sub_res)
```

```{r}
stellate <- RunUMAP(stellate, dims = 1:sub_n_pcs)
DimPlot(stellate, reduction = "umap")
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
FeaturePlot(stellate, features = c("nCount_RNA", "nFeatues_RNA"))
```

```{r}
stellate <- RunTSNE(object = stellate, dims.use = 1:sub_n_pcs, seed.use = 10)
```

```{r}
TSNEPlot(object = stellate, do.label = TRUE)
```

```{r}
suppressMessages(library(biomaRt))
ensembl = useMart("ensembl", dataset = "mmusculus_gene_ensembl")
```

```{r}
n_Gene <- c()
n_UMI <- c()

for(i in names(table(Idents(object = stellate)))) {
  cluster_metadata <- stellate@meta.data[which(Idents(object = stellate) == i),] #For each cluster, extract rows from subs meta data
  n_Gene <- c(n_Gene, mean(cluster_metadata$nFeature_RNA)) #Calculate avg nGene and nUMI
  n_UMI <- c(n_UMI, mean(cluster_metadata$nCount_RNA))
}

cluster_stats <- data.frame(cluster = names(table(Idents(object = stellate))), avg_nGene = n_Gene, avg_nUMI = n_UMI)

print(cluster_stats)
```


```{r}
#DefaultAssay(pdc) <- "integrated"
cl_expr_df <- as.data.frame(AverageExpression(object = stellate))
colnames(cl_expr_df) <- names(table(Idents(object = stellate)))
head(cl_expr_df)
```

```{r}
suppressMessages(library(clusterProfiler))
suppressMessages(library(org.Mm.eg.db))
#----------------------------FIND MARKERS FOR ALL CLUSTERS----------------------------------------
#-------------------------------------------------------------------------------------------------
#Create a list that stores each cluster's markers. 
#The list stores the table of markers as
#Ex: Access the table of markers for cluster 1 with cluster_markers[["c1_markers"]]
cluster_markers <- list()

#Loop through all clusters and find markers for each one
for(i in names(table(Idents(stellate)))) {
  markers <- FindMarkers(object = stellate, ident.1 = i, verbose = FALSE, min.pct = 0.25)
  
  #Retrieve avg UMI for each marker
  markers$avg_UMI <- cl_expr_df[rownames(markers), i]
  
  #Add full gene name as a column
  markers$Gene <- rownames(markers)
  results <- getBM(attributes = c("external_gene_name", "description"), 
                   filters = "external_gene_name",
                   values = rownames(markers), mart = ensembl)
  results <- results[!duplicated(results$external_gene_name),]
  markers <- merge(markers, results, by.x = "Gene", by.y = "external_gene_name", all.x = TRUE)
  
  #Order markers by decreasing avg logFC
  markers <- markers[order(markers$avg_logFC, decreasing = TRUE),]
  
  #Store the markers in the list
  cluster_markers[[i]] <- markers
}
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
FeaturePlot(stellate, features = genes_stellate)
```

```{r}
cluster_markers[["0"]]
```

```{r}
cluster_markers[["1"]]
```

```{r}
cluster_markers[["2"]]
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
FeaturePlot(stellate, features = "Bgn", pt.size = 4)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
FeaturePlot(stellate, features = "Igfbp7", pt.size = 4)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
FeaturePlot(stellate, features = "Col6a3", pt.size = 4)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
FeaturePlot(stellate, features = "Acta2", pt.size = 4)
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
FeaturePlot(stellate, features = "Rbp1", pt.size = 4)
```


```{r, echo=FALSE, fig.height=10, fig.width=15}
FeaturePlot(npc, features = c("Akr1c18", "Ltc4s", "Mgp"), pt.size = 4)
```

```{r, echo=FALSE, fig.height=10, fig.width=15}
FeaturePlot(stellate, features = c("Vcan", "Fn1"), pt.size = 4)
```

```{r, echo=FALSE, fig.height=10, fig.width=15}
VlnPlot(stellate, features = c("Vcan", "Fn1"), pt.size = 4)
```

```{r}
cluster0v2_markers <- FindMarkers(object = stellate, ident.1 = 0, ident.2 = 2, test.use = "wilcox")
cluster0v2_markers <- cluster0v2_markers[order(cluster0v2_markers$avg_logFC, decreasing = TRUE),]

head(cluster0v2_markers)
```

```{r}
avq <- FindMarkers(object = stellate, ident.1 = 1, ident.2 = c(0,2), test.use = "wilcox")
avq <- cluster0v2_markers[order(cluster0v2_markers$avg_logFC, decreasing = TRUE),]

head(cluster0v2_markers)
```


```{r}
# Note: play around with avg_logFC_cutoff
avg_logFC_cutoff <- 0.5
table <- cluster_markers[["1"]]

markers_GO <- (table[which(table$avg_logFC > avg_logFC_cutoff),])$Gene

# Convert gene names that are in ALIAS format into ENTREZID format and GENENAME format
eg <- select(org.Mm.eg.db, markers_GO, c("ENTREZID", "GENENAME"), "ALIAS")

ego <- enrichGO(gene = eg$ENTREZID,   # Analyze using ENTREZID
                OrgDb = org.Mm.eg.db, 
                ont = "BP",           # Select type of ontology: "BP" = biological process
                pAdjustMethod = "BH", # Benjamini-Hochberg procedure is applied for adjusting p-val
                pvalueCutoff = 0.05, 
                qvalueCutoff = 0.01, 
                readable = TRUE)      # Mapping geneID to gene name

head(ego, n = 50)

```

```{r, fig.height=5, fig.width=12}
#Visualize with dotplot
dotplot(ego)
```

```{r}
bec <- SubsetData(object = npc, ident.use = c("bec"))
```

```{r}
bec
print(paste("Avg nGene:", mean(bec$nFeature_RNA), sep = " "))
print(paste("Avg nUMI:", mean(bec$nCount_RNA), sep = " "))
```

```{r}
VlnPlot(object = bec, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
bec <- FindVariableFeatures(object = bec, selection.method = "vst", nfeatures = 2000)
```

```{r}
all.genes <- rownames(x = bec)
bec <- ScaleData(object = bec, features = all.genes)#, vars.to.regress = "orig.ident")
```

```{r}
bec <- RunPCA(bec, features = VariableFeatures(object = bec))
```

```{r}
DimPlot(bec, reduction = "pca")
```

```{r}
ElbowPlot(bec)
```

```{r}
#TODO: Set sub.n.pcs to number of PCs you wish to use.
sub_n_pcs = 10

#TODO: Set resolution 
sub_res <- 0.4
bec <- FindNeighbors(bec, dims = 1:sub_n_pcs)
bec <- FindClusters(bec, resolution = sub_res)
```

```{r}
bec <- RunUMAP(bec, dims = 1:sub_n_pcs)
DimPlot(bec, reduction = "umap")
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
FeaturePlot(bec, features = c("nCount_RNA", "nFeatues_RNA"))
```

```{r}
suppressMessages(library(biomaRt))
ensembl = useMart("ensembl", dataset = "mmusculus_gene_ensembl")
```

```{r}
n_Gene <- c()
n_UMI <- c()

for(i in names(table(Idents(object = bec)))) {
  cluster_metadata <- bec@meta.data[which(Idents(object = bec) == i),] #For each cluster, extract rows from subs meta data
  n_Gene <- c(n_Gene, mean(cluster_metadata$nFeature_RNA)) #Calculate avg nGene and nUMI
  n_UMI <- c(n_UMI, mean(cluster_metadata$nCount_RNA))
}

cluster_stats <- data.frame(cluster = names(table(Idents(object = bec))), avg_nGene = n_Gene, avg_nUMI = n_UMI)

print(cluster_stats)
```


```{r}
#DefaultAssay(pdc) <- "integrated"
cl_expr_df <- as.data.frame(AverageExpression(object = bec))
colnames(cl_expr_df) <- names(table(Idents(object = bec)))
head(cl_expr_df)
```

```{r}
suppressMessages(library(clusterProfiler))
suppressMessages(library(org.Mm.eg.db))
#----------------------------FIND MARKERS FOR ALL CLUSTERS----------------------------------------
#-------------------------------------------------------------------------------------------------
#Create a list that stores each cluster's markers. 
#The list stores the table of markers as
#Ex: Access the table of markers for cluster 1 with cluster_markers[["c1_markers"]]
cluster_markers <- list()

#Loop through all clusters and find markers for each one
for(i in names(table(Idents(bec)))) {
  markers <- FindMarkers(object = bec, ident.1 = i, verbose = FALSE, min.pct = 0.25)
  
  #Retrieve avg UMI for each marker
  markers$avg_UMI <- cl_expr_df[rownames(markers), i]
  
  #Add full gene name as a column
  markers$Gene <- rownames(markers)
  results <- getBM(attributes = c("external_gene_name", "description"), 
                   filters = "external_gene_name",
                   values = rownames(markers), mart = ensembl)
  results <- results[!duplicated(results$external_gene_name),]
  markers <- merge(markers, results, by.x = "Gene", by.y = "external_gene_name", all.x = TRUE)
  
  #Order markers by decreasing avg logFC
  markers <- markers[order(markers$avg_logFC, decreasing = TRUE),]
  
  #Store the markers in the list
  cluster_markers[[i]] <- markers
}
```

```{r, echo=FALSE, fig.height=5, fig.width=10}
FeaturePlot(bec, features = genes_bec)
```

```{r}
cluster_markers[["0"]]
```

```{r}
cluster_markers[["1"]]
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```












